---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttc-products-dev-app
  namespace: ttc-dev
  labels:
    app: ttc-products-dev-app
spec:
  selector:
    matchLabels:
      app: ttc-products-dev-app
      tier: backend
  template:
    metadata:
      labels:
        app: ttc-products-dev-app
        tier: backend
    spec:
      containers:
      - name: ttc-products-dev-app
        image: kranthik123/ttc_products:latest
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: ttc-products-dev-svc
  namespace: ttc-dev
  labels:
    service: ttc-products-dev-svc
spec:
  selector:
    app: ttc-products-dev-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4000
  type: LoadBalancer
